# Generated by Django 4.2.3 on 2023-07-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_useraccount_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="administrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.administrator"
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="batch_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.batch"
            ),
        ),
    ]
