# Generated by Django 4.2.3 on 2023-09-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_intern_tasks_tasks_intern"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="batch_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
