# Generated by Django 4.2.3 on 2023-09-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_batch_batch_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
    ]
