# Generated by Django 4.2.3 on 2023-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_batch_administrator_id_batch_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="last_login",
            field=models.DateField(auto_now=True),
        ),
    ]
