# Generated by Django 4.2.3 on 2023-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_useraccount_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
