# Generated by Django 4.2.3 on 2023-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_useraccount_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
